package com.freshvotes.domain;
// Generated Aug 1, 2020 4:36:21 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name = "DEPARTMENTS",
         schema = "HR"
)
@XmlRootElement(name = "employee")
public class Departments implements java.io.Serializable {

    private short departmentId;
    private Locations locations;
    private Employees employees;
    private String departmentName;
    private Set<Employees> employeeses = new HashSet<Employees>(0);

    public Departments() {
    }

    public Departments(short departmentId, String departmentName) {
        this.departmentId = departmentId;
        this.departmentName = departmentName;
    }

    public Departments(short departmentId, Locations locations, Employees employees, String departmentName, Set<Employees> employeeses) {
        this.departmentId = departmentId;
        this.locations = locations;
        this.employees = employees;
        this.departmentName = departmentName;
        this.employeeses = employeeses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO,generator = "DEPARTMENTS_SEQ")
    @SequenceGenerator(name = "DEPARTMENTS_SEQ" ,sequenceName = "DEPARTMENTS_SEQ")
    @Column(name = "DEPARTMENT_ID", unique = true, nullable = false, precision = 4, scale = 0)
    public short getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(short departmentId) {
        this.departmentId = departmentId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "LOCATION_ID")
    public Locations getLocations() {
        return this.locations;
    }

    public void setLocations(Locations locations) {
        this.locations = locations;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "MANAGER_ID")
    public Employees getEmployees() {
        return this.employees;
    }

    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

    @Column(name = "DEPARTMENT_NAME", nullable = false, length = 30)
    public String getDepartmentName() {
        return this.departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "departments")
    public Set<Employees> getEmployeeses() {
        return this.employeeses;
    }

    public void setEmployeeses(Set<Employees> employeeses) {
        this.employeeses = employeeses;
    }

}
